name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - '*'
    - '!badges'


jobs:
  build:
    name: FM4SE | Alloy Signature Checker
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout Starter Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute tests
        run: curl -s https://gist.githubusercontent.com/soaibsafi/29596e0d44ec59bce355923ee81bba66/raw/e510892bde3185f96005d3a56c0d91ead835994a/alloy_sig_checker_tests.sh | bash -s
    
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Display Java version
        run: java -version
      
      - name: Grading
        uses: education/autograding@v1
        id: autograder
        continue-on-error: true
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Generate Report
      - run: python generate_report.py

      # switch to badges branch
      - run: git checkout badges || git checkout -b badges
      
      # create points bar
      - name: points bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.autograder.outputs.points }}
          path: '.github/badges/points-bar.svg'

      # commit and push badges if badges have changed
      - name: Commit changes to points bar
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points-bar.svg'
          git add 'report.md'
          git commit -m "Add/Update report" || exit 0
          git push -f origin badges
